- name: install rabbitmq on linux server
  hosts: rabbitmq
  become: yes
  tasks:
  - name: download repo
    ansible.builtin.command: curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.rpm.sh | bash

  - name: install rabbit mq
    ansible.builtin.yum:
      name: rabbitmq-server
      state: installed
  - name: start and enable rabbit mq
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes
  
  - name: set default uer name
    ansible.builtin.command: rabbitmqctl add_user roboshop roboshop123

  - name: set permissions
    ansible.builtin.command: rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"